---
- hosts: windows
  tasks:
    - name: Test connection
      win_ping:
    
    - name: Installing IIS
      win_feature:
        name: "Web-Server"
        state: present
        restart: yes
        include_sub_features: yes
        include_management_tools: yes

    - name: Restarting the web app pool
      win_iis_webapppool:
         name: "DefaultAppPool"
         state: restarted

  handlers:
    - name: w3svc reset
      win_service:
        name: w3svc
        state: restarted